### ISSUE TITLE
problem with BlobTracker and params

### ISSUE THREAD

**Issue by Gdlv** [baggepinnen/BlobTracking.jl#15]
Hello!
I had been working in R with video tracking of insects but now I want to migrate to Julia. 
I am learning Julia now, and I could not reproduce the example with my own video test. 
I am stopped in: 
```julia
bt = BlobTracker(sizes=3:3,
                mask=mask,
                preprocessor = preprocessor,
                amplitude_th = 0.05,
                correspondence = HungarianCorrespondence(p=1.0, dist_th=2), # dist_th is the number of sigmas away from a predicted location a measurement is accepted.
                σw = 2.0, # Dynamics noise std.
                σe = 10.0)  # Measurement noise std. (pixels)

UndefKeywordError: keyword argument params not assigned

Stacktrace:
 [1] top-level scope at In[5]:2
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```

As I said, I am new in Julia. Where is the wrong step? The prepocessor function maden in the previous step needs something else? 

I am working in Win10 with Atom and Julia 1.5.1.

**Comment by baggepinnen** [comment]
It looks like the readme documentation is out of date. You can try to call the method listed below, i.e., move `sizes, σw, σe` to positional arguments and kep the rest as keyword arguments. Alternatively, supply `KalmanParams` manually as below.
```julia
"""
    BlobTracker(sizes, σw, σe; kwargs...)
Helper constructor that accepts keyword arguments for the `KalmanParams`
#Arguments:
- `σw`: Dynamics standard deviation
- `σe`: Measurement standard deviation
"""
function BlobTracker(sizes, σw, σe; kwargs...)
    BlobTracker(;sizes = sizes, params = KalmanParams(σw, σe), kwargs...)
end
```
